name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PIP_CACHE_DIR: ~/.cache/pip

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip requirements
      id: pip-cache
      uses: actions/cache@v2
      with:
        path: ${{ env.PIP_CACHE_DIR }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.*') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Verify Python environment
      run: |
        pip list
        pip cache list

    - name: Install dependencies
      run: |
        pip install -e .[tests]

    - name: Run tests
      run: pytest -s -v -n auto

    - name: Upload coverage
      if: ${{ success() && matrix.python-version == '3.7' }}
      run: |
        pip install coveralls
        coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-more:
    name: test (${{ matrix.os }}, ${{ matrix.miniforge-variant }})
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos", "windows"]
        include:
          - os: ubuntu
            environment-file: .github/environment_pypy.yml
            miniforge-variant: Mambaforge-pypy3
          - os: macos
            environment-file: .github/environment.yml
            miniforge-variant: Mambaforge
          - os: windows
            environment-file: .github/environment.yml
            miniforge-variant: Mambaforge
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Cache conda
      uses: actions/cache@v2
      env:
        # Increase this value to reset cache if environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: ${{ matrix.miniforge-variant }}
        environment-file: ${{ matrix.environment-file }}
        condarc-file: .github/condarc.yml
        use-mamba: true

    - name: Verify Python environment
      shell: bash -l {0}
      run: |
        mamba list
        python --version

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        python -m pip install -e .[tests]

    - name: Run tests
      shell: bash -l {0}
      run: |
        python -m pytest -s -v -n auto

    - name: Run mypy
      shell: bash -l {0}
      run: |
        python -m mypy ./pymech --show-error-codes
